# Generated by Django 4.2.5 on 2023-09-16 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('profile_pic', models.ImageField(default='profile.jpg', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Homo Sapiens', 'Homo Sapiens'), ('Women', 'Women'), ('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Homo Sapiens', max_length=15)),
                ('phone', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('descprition', models.TextField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('prompt', models.TextField(null=True)),
                ('response', models.TextField(null=True)),
                ('prompt_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
